FROM adoptopenjdk/openjdk13:x86_64-alpine-jre13u-nightly

ENV JAR=course-service-1.0.0.jar

WORKDIR /APP

COPY $JAR .


ENTRYPOINT java -jar $JAR
#CMD while true; do sleep 1000; done
#CMD java -jar /APP/$JARFILE

EXPOSE 8000