- hosts: localhost
  tags: infrastructuresetup
  become: false
  gather_facts: no
  vars:
    state: absent
    project_name: demo
    environmentid: test
    region: eu-central-1
    instance_types: t3a.small,t3a.medium,t3a.large
    kubeconfig: /home/lukas/.kube/eks.config
  roles:
    - infrastructure