- hosts: localhost
  tags: infrastructuresetup
  become: false
  gather_facts: no
  tasks:
    - name: infrastructureProvisioning
      vars:
        jupyterhub_version: 0.11.1
        jupyter_release_name: jhub
        jupyter_namespace_name: jhub
        state: present
        imagename: luke19/jenkins
        imagetag: v0.8
        K8S_AUTH_KUBECONFIG: "/home/lukas/.kube/eks-{{ item }}.config"
      include_role:
        name: kube
      with_items:
        - eu-central-1
        - eu-west-1