init:
	sudo terraform init


plan:
	sudo terraform plan


run:
	sudo terraform apply


remove:
	sudo terraform destroy


list-workspace:
	sudo terraform workspace list


new-workspace:
	sudo terraform workspace new $(name)


select-workspace:
	sudo terraform workspace select $(name)


remove-workspace:
	sudo terraform workspace delete $(name)


build-frontend:
	npm run build --prefix ./frontend


deploy-frontend:
	npm run deploy --prefix ./frontend