/**
 * Course Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { Course } from '../model/course';
import { CourseOverview } from '../model/courseOverview';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CoursesService {

    protected basePath = 'http://api/course';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Delete a course
     * 
     * @param courseid Course ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteCourse(courseid: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteCourse(courseid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteCourse(courseid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteCourse(courseid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (courseid === null || courseid === undefined) {
            throw new Error('Required parameter courseid was null or undefined when calling deleteCourse.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.configuration.basePath}/courses/${encodeURIComponent(String(courseid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a course
     * 
     * @param courseid Course ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCourse(courseid: string, observe?: 'body', reportProgress?: boolean): Observable<Course>;
    public getCourse(courseid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Course>>;
    public getCourse(courseid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Course>>;
    public getCourse(courseid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (courseid === null || courseid === undefined) {
            throw new Error('Required parameter courseid was null or undefined when calling getCourse.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Course>(`${this.configuration.basePath}/courses/${encodeURIComponent(String(courseid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all courses
     * 
     * @param userid User ID
     * @param deleted Deleted Flag
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCourses(userid?: string, deleted?: boolean, observe?: 'body', reportProgress?: boolean): Observable<Array<CourseOverview>>;
    public getCourses(userid?: string, deleted?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CourseOverview>>>;
    public getCourses(userid?: string, deleted?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CourseOverview>>>;
    public getCourses(userid?: string, deleted?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (userid !== undefined && userid !== null) {
            queryParameters = queryParameters.set('userid', <any>userid);
        }
        if (deleted !== undefined && deleted !== null) {
            queryParameters = queryParameters.set('deleted', <any>deleted);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<CourseOverview>>(`${this.configuration.basePath}/courses`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create a course
     * 
     * @param courseOverview 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postCourses(courseOverview: CourseOverview, observe?: 'body', reportProgress?: boolean): Observable<Course>;
    public postCourses(courseOverview: CourseOverview, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Course>>;
    public postCourses(courseOverview: CourseOverview, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Course>>;
    public postCourses(courseOverview: CourseOverview, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (courseOverview === null || courseOverview === undefined) {
            throw new Error('Required parameter courseOverview was null or undefined when calling postCourses.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Course>(`${this.configuration.basePath}/courses`,
            courseOverview,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update the course
     * 
     * @param courseid Course ID
     * @param course 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putCourse(courseid: string, course: Course, observe?: 'body', reportProgress?: boolean): Observable<Course>;
    public putCourse(courseid: string, course: Course, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Course>>;
    public putCourse(courseid: string, course: Course, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Course>>;
    public putCourse(courseid: string, course: Course, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (courseid === null || courseid === undefined) {
            throw new Error('Required parameter courseid was null or undefined when calling putCourse.');
        }
        if (course === null || course === undefined) {
            throw new Error('Required parameter course was null or undefined when calling putCourse.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<Course>(`${this.configuration.basePath}/courses/${encodeURIComponent(String(courseid))}`,
            course,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Restore a course
     * 
     * @param courseid Course ID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public restoreCourse(courseid: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public restoreCourse(courseid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public restoreCourse(courseid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public restoreCourse(courseid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (courseid === null || courseid === undefined) {
            throw new Error('Required parameter courseid was null or undefined when calling restoreCourse.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.post<any>(`${this.configuration.basePath}/courses/${encodeURIComponent(String(courseid))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
