server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://localhost:39000/lernplattform
    username: internaluser
    password: lernplattform
    driver-class-name: org.postgresql.Driver