- hosts: localhost
  tags: infrastructuresetup
  become: false
  gather_facts: no
  vars:
    state: present
    app: jumphost-hardening
    environmentid: test
    region: eu-central-1
    instance_type: t2.micro
    ami_bastion: ami-0db9040eb3ab74509
    ami_webserver: ami-0767046d1677be5a0
    cidr_block: 10.0.0.0/16
    subnet_public_cidr_block: 10.0.0.0/24
    subnet_private_cidr_block: 10.0.1.0/24
    key_name: bastionkeypair
    ip_adresses:
      - 84.114.17.129/32
      - 172.10.0.0/32
      - 1.2.3.4/32
    ssh_port: 222
    ssh_config_name: jumphost_config
  roles:
    - infrastructure