openapi: "3.0.0"
info:
  version: 1.0.0
  title: Course Service
servers:
  - url: api/course
paths:
  /courses:
    get:
      summary: Get all courses
      operationId: getCourses
      tags:
        - courses
      parameters:
        - $ref: "#/components/parameters/userid"
        - $ref: "#/components/parameters/deleted"
      responses:
        200:
          description: Courses
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/CourseOverviewList'
    post:
      summary: Create a course
      operationId: postCourses
      tags:
        - courses
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseOverview'
      responses:
        200:
          description: Created a course
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Course"
  /courses/{courseid}:
    parameters:
      - $ref: '#/components/parameters/courseid'
    get:
      summary: Get a course
      operationId: getCourse
      tags:
        - courses
      responses:
        200:
          description: Course
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Course'
    put:
      summary: Update the course
      operationId: putCourse
      tags:
        - courses
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        200:
          description: The updated course
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
    post:
      summary: Restore a course
      operationId: restoreCourse
      tags:
        - courses
      responses:
        204:
          description: The course has been restored
    delete:
      summary: Delete a course
      operationId: deleteCourse
      tags:
        - courses
      responses:
        204:
          description: The course has been deleted
  /courses/{courseid}/tasks:
    parameters:
      - $ref: '#/components/parameters/courseid'
    get:
      summary: Get the tasks of a course
      operationId: getTasks
      tags:
        - tasks
      responses:
        200:
          description: Course
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Tasks'
    post:
      summary: Create a task
      operationId: postTask
      tags:
        - tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        200:
          description: Created a Task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
  /courses/{courseid}/tasks/{taskid}:
    parameters:
      - $ref: '#/components/parameters/courseid'
      - $ref: '#/components/parameters/taskid'
    get:
      summary: Get a task
      operationId: getTask
      tags:
        - tasks
      responses:
        200:
          description: Task
          content:
            application/json:
                schema:
                  $ref: '#/components/schemas/Task'
    put:
      summary: Update a task
      operationId: putTask
      tags:
        - tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        200:
          description: The updated task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    delete:
      summary: Delete a task
      operationId: deleteTask
      tags:
        - tasks
      responses:
        204:
          description: The task has been deleted
  /courses/{courseid}/tasks/{taskid}/feedback:
    parameters:
      - $ref: '#/components/parameters/courseid'
      - $ref: '#/components/parameters/taskid'
    put:
      summary: Get feedback for a task
      operationId: putFeedback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Feedback_Request'
      responses:
        200:
          description: The feedback
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feedback_Response'
components:
  parameters:
    courseid:
      name: courseid
      in: path
      required: true
      description: Course ID
      schema:
        type: string
    deleted:
      name: deleted
      in: query
      required: false
      description: Deleted Flag
      schema:
        type: boolean
    taskid:
      name: taskid
      in: path
      required: true
      description: Task ID
      schema:
        type: string
    userid:
      name: userid
      in: query
      required: false
      description: User ID
      schema:
        type: string
    feedback:
      name: feedback
      in: query
      required: true
      schema:
        type: string
    solved:
      name: solved
      required: true
      in: query
      schema:
        type: string
  responses:
    Error:
      description: Error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    CourseOverviewList:
      type: array
      items:
        $ref: '#/components/schemas/CourseOverview'
    CourseOverview:
      properties:
        id:
          type: string
        name:
          type: string
        deleted:
          type: boolean
        schema:
          type: int
    Course:
      properties:
        id:
          type: string
        name:
          type: string
        deleted:
          type: boolean
        schema:
          type: int
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'
    Tasks:
      type: array
      items:
        $ref: '#/components/schemas/Task'
    Task:
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        code:
          type: string
        previousTask:
          type: string
        nextTask:
          type: string
    Feedback_Request:
      properties:
        solved:
          type: string
        taskid:
          type: string
        courseid:
          type: string
    Feedback_Response:
      properties:
        feedback:
          type: string
    Error:
      properties:
        message:
          type: string
      required:
        - message
