openapi: "3.0.0"
info:
  version: 1.0.0
  title: User Service
servers:
  - url: api/user
paths:
  /users/login:
    post:
      summary: Login with email and password
      operationId: login
      tags:
        -  login
      requestBody:
        description: Source
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        200:
          description: Token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
components:
  schemas:
    Token:
      required:
        - token
        - userid
      properties:
        token:
          type: string
        userid:
          type: string
    Login:
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 1
          maxLength: 40
