
# tasks file for infrastructure
---
- name: check if cluster already exists
  shell: |
    eksctl get cluster \
    --name "{{ project_name }}-{{ environmentid }}-{{ region }}-cluster" \
    --region "{{ region }}"
  register: cluster
  ignore_errors: True
  when: state == "present" or state == "Update"

- name: create cluster
  shell: | 
    eksctl create cluster \
    --name "{{ project_name }}-{{ environmentid }}-{{ region }}-cluster" \
    --managed --spot \
    --instance-types "{{ instance_types }}" \
    --asg-access \
    --nodes "{{ min_nodes }}" \
    --nodes-min "{{ min_nodes }}" \
    --nodes-max "{{ max_nodes }}" \
    --region "{{ region }}" \
    --kubeconfig "{{ kubeconfig }}" \
    --tags project="{{ project_name }}"
  when: state == "present" and cluster.failed == true

- name: delete cluster
  shell: | 
    eksctl delete cluster \
    --name "{{ project_name }}-{{ environmentid }}-{{ region }}-cluster" \
    --region "{{ region }}"
  ignore_errors: True
  when: state == "absent"