
# tasks file for infrastructure
---
- name: terraforming
  terraform:
    project_path: "{{ playbook_dir }}/roles/infrastructure/terraform"
    force_init: true
    state: "{{ state }}"
    variables:
      cluster_name: "{{ project_name }}"
      environment: "{{ environmentid }}"
      region: "{{ region }}"
      cidr_block: "{{cidr_block}}"
      subnet_public_cidr_block: "{{ subnet_public_cidr_block }}"
      subnet_private_cidr_block: "{{ subnet_private_cidr_block }}"
  register: tf


- debug:
    msg: "{{tf}}"